[package]
name = "ugradrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
uuid = { version = "1.3.4", features = ["v4"]}
petgraph = {version = "0.6.3", optional = true }

[features]
draw_graph = ["dep:petgraph"]

[dev-dependencies]
approx = "0.5.1"
rstest = "0.17"
rand_distr = "0.4"
